[package]
name = "rba"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.128.3"
cranelift-jit = "0.128.3"
cranelift-module = "0.128.3"
cranelift-codegen = "0.128.3"
cranelift-native = "0.128.3"
pom = "3.4.0"
libc = "0.2.182"
rba-derive = { version = "0.1.0", path = "rba-derive" }

[profile.dev]
# figure out why this is here first...
# overflow-checks = false
